#pragma once

#include"Bin.h"
#include"CharArray.h"
#include"Decode.h"
#include"Encode.h"
#include"PaiDivide.h"
#include"OutPaiDivide.h"
#include"InPaiDivide.h"
#include"PaiMatch.h"
#include"OutPaiMatch.h"
#include"InPaiMatch.h"
#include"CharArrayNumeric.h"
#include"Quinary.h"
#include"DiceEncode.h"
#include"DiceDecode.h"
#include"StringDecode.h"
#include"StringEncode.h"
#include"StringMatching.h"
#include"CharPositions.h"
#include"StringPositions.h"
